#!/bin/sh -x

REPO="$1"

REPO_NAME="$(echo "$REPO" | cut -d'.' -f1)"

test -d "/srv/http/git/${REPO_NAME}" || mkdir "/srv/http/git/${REPO_NAME}"

cd /srv/http/git/${REPO_NAME}
stagit /srv/git/${REPO}

cp /srv/http/git/style.css /srv/http/git/${REPO_NAME}
cp /srv/http/git/logo.png /srv/http/git/${REPO_NAME}

cd /srv/http/git
stagit-index /srv/git/*.git > index.html

echo "Done."
