#!/bin/sh -x

REPO="$1"

REPO_NAME="$(echo "$REPO" | cut -d'.' -f1)"

test -d "/srv/http/git/${REPO_NAME}" || mkdir "/srv/http/git/${REPO_NAME}"

cd /srv/http/git/${REPO_NAME}
stagit /srv/git/${REPO}

cp /srv/http/git/style.css /srv/http/git/${REPO_NAME}
cp /srv/http/git/logo.png /srv/http/git/${REPO_NAME}

cd /srv/http/git
list=""
for repo in /srv/git/*.git; do
    [ -f "$repo/git-daemon-export-ok" ] && list="$repo $list"
done
stagit-index $list > index.html

echo "Done."
