title: "tudor's swamp"
subtitle: "The web site of Tudor Roman"
description: "This is tudurom's webspace. Here I share different kinds of information hoping that it will be useful for someone."
keywords: "random site website tudor roman tudurom useful git blog github swamp golang go orator"
author: "Tudor Roman"
basePath: ""
extra:
    themecolor: "#1c4b4e"
